version: '3.5'

services:
  functional-unit-commands:
    image: registry.redmic.net/redmic-server/${UNIT_NAME}:${IMAGE_TAG:-latest}
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVICE
      - JAVA_OPTS=-Xmx512m -Xss512m
    networks:
      - kafka-net
      - redmic-net
    volumes:
      - commands-vol:/tmp/kafka
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${COMMANDS_PORT}/api/${UNIT_NAME}/commands/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  kafka-net:
    external: true
  redmic-net:
    external: true
