version: '3.5'

services:
  template-commands:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - COMMANDS_PORT
      - SPRING_PROFILES_ACTIVE
      - MICROSERVICE_NAME=${UNIT_NAME}-commands
      - SPRING_KAFKA_CLIENT-ID={{.Service.Name}}-{{.Task.Slot}}
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    networks:
      - metric-net
      - kafka-net
      - redmic-net
      - traefik-net
    volumes:
      - commands-vol:/tmp/kafka
    healthcheck:
      test: wget --spider -q http://localhost:${COMMANDS_PORT}/api/${UNIT_NAME}/commands/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:${PUBLIC_HOSTNAME};PathPrefix:/api/${UNIT_NAME}/commands
        traefik.backend: ${UNIT_NAME}-commands
        traefik.port: '${COMMANDS_PORT}'
      restart_policy:
        delay: 10s
        window: 3m

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

  redmic-net:
    name: ${REDMIC_NET_NAME:-redmic-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  commands-vol:
    name: '${UNIT_NAME}-commands-{{.Task.Slot}}-vol'
